//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AldeaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Pagos
    {
        public int IdPagos { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string AnioPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<double> ValorPago { get; set; }
    }
}
