//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AldeaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_AldeaEntities : DbContext
    {
        public DB_AldeaEntities()
            : base("name=DB_AldeaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tb_Pagos> Tb_Pagos { get; set; }
        public virtual DbSet<Tb_ParametrosInformativos> Tb_ParametrosInformativos { get; set; }
        public virtual DbSet<Tb_Usuarios> Tb_Usuarios { get; set; }
    }
}
